// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXa5bASIPF_KcpinFFwN7LKHKzgC2574',
    appId: '1:611912169617:web:38d0ec88a1e24874736730',
    messagingSenderId: '611912169617',
    projectId: 'chiayi-explorer-luc-d0da1',
    authDomain: 'chiayi-explorer-luc-d0da1.firebaseapp.com',
    storageBucket: 'chiayi-explorer-luc-d0da1.firebasestorage.app',
    measurementId: 'G-LTLNV7N4VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ZZ4XkAOSs0Rl84vljcbF0ILZ9tB97-k',
    appId: '1:611912169617:android:7718fcc794f4ba58736730',
    messagingSenderId: '611912169617',
    projectId: 'chiayi-explorer-luc-d0da1',
    storageBucket: 'chiayi-explorer-luc-d0da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQdZU82sJX8IEYofDaK0UIr3of6PTgQw',
    appId: '1:611912169617:ios:48b7cf3956981fdf736730',
    messagingSenderId: '611912169617',
    projectId: 'chiayi-explorer-luc-d0da1',
    storageBucket: 'chiayi-explorer-luc-d0da1.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQdZU82sJX8IEYofDaK0UIr3of6PTgQw',
    appId: '1:611912169617:ios:48b7cf3956981fdf736730',
    messagingSenderId: '611912169617',
    projectId: 'chiayi-explorer-luc-d0da1',
    storageBucket: 'chiayi-explorer-luc-d0da1.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXa5bASIPF_KcpinFFwN7LKHKzgC2574',
    appId: '1:611912169617:web:903a974cdf88399f736730',
    messagingSenderId: '611912169617',
    projectId: 'chiayi-explorer-luc-d0da1',
    authDomain: 'chiayi-explorer-luc-d0da1.firebaseapp.com',
    storageBucket: 'chiayi-explorer-luc-d0da1.firebasestorage.app',
    measurementId: 'G-9FZ0N5ELQ6',
  );
}
